### ISSUE TITLE
Can't build only for darwin platform and x64 architecture.

### ISSUE THREAD

**Issue by crushedice2000** [Urucas/electron-packager-interactive#20]
I can't build any app for darwin x64. It trows me this error message:

    ✗ Sorry, building for darwin ia32 is not supported by Electron

However, I didn't check the `ia32` architecture checkbox when prompted.

[![asciicast](https://asciinema.org/a/101186.png)](https://asciinema.org/a/101186)

**Comment by zeke** [comment]
I am getting this same error. I did not select `ia32`.

![screen shot 2017-01-31 at 9 40 42 pm](https://cloud.githubusercontent.com/assets/2289/22496396/385b864e-e7fe-11e6-94e8-affb0aa649e4.png)

**Comment by mitchellnemitz** [comment]
Same error, clearly did not select `ia32`:

![image](https://cloud.githubusercontent.com/assets/1457482/22698643/18edcb3a-ed23-11e6-8012-0c1da2993b4c.png)

**Comment by crushedice2000** [comment]
Let's wait until somebody merges the Pull Request #21 which fixes this.

**Comment by papakay** [comment]
I have tried this but still getting the same error.

**Comment by crushedice2000** [comment]
@papakay: Are you using the last version?

**Comment by papakay** [comment]
@crushedice2000 , Yes i am using the latest version. In fact i installed it when the update has been made. So my version has the commit changes referenced by @vrunoa

**Comment by crushedice2000** [comment]
Please zip the installation that you're running and send me it. This looks so strange.

**Comment by vrunoa** [comment]
@papakay are you using the lib directly from github and not installing it via npm ? make sure you re-build the module with my changes

**Comment by papakay** [comment]
@crushedice2000, please kindly follow this link for the zip file requested. https://www.dropbox.com/s/umsagsnkyknterm/electron-packager-interactive.zip?dl=0 

@vrunoa i used npm to install it this way ```npm install electron-packager-interactive -g```

Thank you

**Comment by crushedice2000** [comment]
@papakay: Sorry. I did something wrong. The PR #22 fixes it.

**Comment by crushedice2000** [comment]
@papakay: Please try the latest version. Sorry. It was a mistake.
