### ISSUE TITLE
Deprecations Warnings

### ISSUE THREAD

**Issue by SaraVieira** [Urucas/electron-packager-interactive#24]
Hello,

When running I am getting a couple of deprecation errors:
<img width="1053" alt="screen shot 2017-05-31 at 11 39 10" src="https://cloud.githubusercontent.com/assets/1051509/26628414/e9d21e24-45f5-11e7-9131-c5ec7285478d.png">

Need help with this ?

**Comment by vrunoa** [comment]
@SaraVieira i'll take a look as soon as I can

**Comment by SaraVieira** [comment]
@vrunoa Awesome !

**Comment by vrunoa** [comment]
published `electron-packager-interactive@0.1.1`

**Comment by SaraVieira** [comment]
Two of them are gone but one is still here :

```
WARNING: The version parameter is deprecated, use electronVersion (or --electron-version in the CLI) instead
```

**Comment by vrunoa** [comment]
@SaraVieira I follow their documentation 
https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#electronversion
in the next days i'll check if there's an issue on their side

**Comment by SaraVieira** [comment]
@vrunoa Oh , yeah , it's their issue now :)

Thank you
I'll close the issue :)
