### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by Wilsonilo** [Urucas/electron-packager-interactive#3]
Hey, great job!
I know that with the original electron package you can manage the icon option.
How about in this one?

**Comment by Wilsonilo** [comment]
One more, may be stupid question, but i'm just starting. It seems that the "original" electron-packager do not pack on 32 but this one it does. Why is that?

**Comment by vrunoa** [comment]
@Wilsonilo I forgot to add the **icon** implementation, i'll create an issue and will add it before the end of the week. 
```electron-packager``` do pack on 32bits, this lib it0s just a wrapper for that lib. Why do you say you cant pack on 32bits with ```electron-packager``` ?

**Comment by Wilsonilo** [comment]
:D the icon issue sounds great!
electron-packager not sure it only delivers x64, i use "all" arch and platform "darwin" and just delivers x64.

**Comment by vrunoa** [comment]
mmm that may be a mistake on the ```electron-packager-interactive```, have you try selecting just **ia32** to see if the package is built?

**Comment by Wilsonilo** [comment]
Yeah, if i use ia32 on electron-packager do not delivers the app but electron-packager-interactive it does.
I'm using "El Capitan" dunno if that has something to do with it, i'll try in a few hours changing values and let you know

**Comment by vrunoa** [comment]
I'm still on **Yosemite** can't tell if this issue has to do with your **osx** version. Maybe depends on the ```electron-packager``` version. For ```electron-packager-interactive``` we use
```json
"electron-packager": "^5.0.2",
```
what version did u install on your project ? 
Have any link where I cant test or see how are you creating the ```electron-packager``` settings ?

**Comment by vrunoa** [comment]
hey @Wilsonilo there's a new release of [electron-packager-interactive](https://www.npmjs.com/package/electron-packager-interactive) with the ```icon``` option.

**Comment by Wilsonilo** [comment]
Hey man awesome! @vrunoa thanks, just updated!
