### ISSUE TITLE
Building for darwin ia32 silently fails

### ISSUE THREAD

**Issue by adam-lynch** [Urucas/electron-packager-interactive#7]
It says it's successful. I think the bug is not showing an error / allowing the arch choice.

**Comment by vrunoa** [comment]
@adam-lynch it fails to create the final app ? Does it start building ?

**Comment by adam-lynch** [comment]
It shows the success message but where the output directory should be, it's just an empty string.

**Comment by vrunoa** [comment]
@adam-lynch maybe there's a problem with the input folder. Can you give me a log output I can check on ?

**Comment by antoinepairet** [comment]
electron-packager which is used under the hood does not `ia32` target for OSX. 
Running `electron-packager . yourApp --platform=darwin --arch=ia32` will do nothing. No warning will be logged.

Conclusion: it is not an issue with `electron-packager-interactive` itself but with `electron-packager`
A warning would be welcome :-). Can be done here or in `electron-packager`

**Comment by vrunoa** [comment]
cool @antoinepairet , didn't know about this. I'll add a warning message in case ```electron-packager``` module don't add it.

**Comment by vrunoa** [comment]
Done. There's a warning to the user that building for darwin ia32 will fail.

https://github.com/Urucas/electron-packager-interactive/blob/master/lib/index.js#L133-L141
